### ISSUE TITLE
IndexOutOfBoundsException in org.opensaml.xml.util

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#26]
[DEBUG] WebBrowserSSOProfile Audience set in local AuthenticationContext (https://xxxxxxx/asimba/profiles/saml2)
[DEBUG] AbstractAuthNMethodSAML2Profile Adding attribute to map: eduPersonPrincipalName
[ERROR] AuthenticationManager Internal error during authentication
java.lang.IndexOutOfBoundsException: Index: 0
     at java.util.Collections$EmptyList.get(Collections.java:3212)
     at org.opensaml.xml.util.LazyList.get(LazyList.java:90)
     at org.opensaml.xml.util.XMLObjectChildrenList.get(XMLObjectChildrenList.java:97)
     at org.opensaml.xml.util.XMLObjectChildrenList.get(XMLObjectChildrenList.java:33)
     at com.alfaariss.oa.authentication.remote.saml2.profile.AbstractAuthNMethodSAML2Profile.getAttributeMap(AbstractAuthNMethodSAML2Profile.java:485)
    at com.alfaariss.oa.authentication.remote.saml2.profile.sso.WebBrowserSSOProfile.handleResponse(WebBrowserSSOProfile.java:743)
    at com.alfaariss.oa.authentication.remote.saml2.profile.sso.WebBrowserSSOProfile.process(WebBrowserSSOProfile.java:190)
    at com.alfaariss.oa.authentication.remote.saml2.SAML2AuthenticationMethod.authenticate(SAML2AuthenticationMethod.java:339)
     at com.alfaariss.oa.sso.authentication.web.AuthenticationManager.authenticate(AuthenticationManager.java:146)
    at com.alfaariss.oa.sso.web.profile.web.WebProfile.handleAuthentication(WebProfile.java:1245)
    at com.alfaariss.oa.sso.web.profile.web.WebProfile.service(WebProfile.java:442)
    at com.alfaariss.oa.sso.web.WebSSOServlet.service(WebSSOServlet.java:238)

**Comment by dmogn** [comment]
Fixed.

**Comment by dmogn** [comment]
There is attribute statement with empty value inside on input.
Now Asimba should just ignore this case of attributes with empty XML value (with an ERROR message to log).

**Comment by dmogn** [comment]
Or Asimba should provide an attribute with empty value? ...

**Comment by nynymike** [comment]
Good question. I think it should include the attribute with an empty value... that way we know the attribute would have been sent.

**Comment by dmogn** [comment]
Done. Now it process empty value attributes.
