### ISSUE TITLE
Asimba - OpenLDAP exception

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#30]
(ASIMBAWA) [2016-12-04 18:43:58] [ERROR] LDAPUtility cannot open LdapEntryManager
java.lang.NullPointerException
        at org.gluu.asimba.util.ldap.LDAPUtility.getLDAPEntryManager(LDAPUtility.java:148)
        at org.gluu.asimba.util.ldap.LDAPUtility.getLDAPEntryManagerSafe(LDAPUtility.java:172)
        at org.gluu.asimba.util.ldap.LDAPUtility.<clinit>(LDAPUtility.java:83)
        at com.alfaariss.oa.util.saml2.SAML2RequestorsLDAP.<init>(SAML2RequestorsLDAP.java:73)
        at com.alfaariss.oa.profile.saml2.SAML2Profile.init(SAML2Profile.java:204)
        at com.alfaariss.oa.OAServlet.loadProfiles(OAServlet.java:389)
        at com.alfaariss.oa.OAServlet.start(OAServlet.java:136)
        at com.alfaariss.oa.OAServlet.init(OAServlet.java:100)

(ASIMBAWA) [2016-12-04 18:43:58] [ERROR] LDAPUtility com.alfaariss.oa.OAException: 0011
(ASIMBAWA) [2016-12-04 18:43:58] [ERROR] LDAPUtility Failed to load AsimbaConfiguration from LDAP Appliance
java.lang.NullPointerException
        at org.gluu.asimba.util.ldap.LDAPUtility.loadAsimbaConfiguration(LDAPUtility.java:181)
        at org.gluu.asimba.util.ldap.LDAPUtility.getDnForAsimbaData(LDAPUtility.java:324)
        at org.gluu.asimba.util.ldap.LDAPUtility.getDnForLDAPRequestorEntry(LDAPUtility.java:296)
        at org.gluu.asimba.util.ldap.LDAPUtility.loadRequestors(LDAPUtility.java:217)
        at com.alfaariss.oa.util.saml2.SAML2RequestorsLDAP.<init>(SAML2RequestorsLDAP.java:73)
        at com.alfaariss.oa.profile.saml2.SAML2Profile.init(SAML2Profile.java:204)
        at com.alfaariss.oa.OAServlet.loadProfiles(OAServlet.java:389)
        at com.alfaariss.oa.OAServlet.start(OAServlet.java:136)
        at com.alfaariss.oa.OAServlet.init(OAServlet.java:100)

**Comment by tecoholic** [comment]
Is there a specific place for ASIMBA where the Ldap properties like `bindDN`  are stored?

**Comment by nynymike** [comment]
it should be using ox-ldap.properties

**Comment by dmogn** [comment]
Fixed.
An other issue:
[ERROR] ApplicationSelectorConfiguration Failed to load mapping from 'asimba-selector.xml'. The environment variable catalina.home isn't defined
Fixing...

**Comment by yurem** [comment]
@dmogn you need to use gluu.base variable isntead of catalina.home
Jetty oxAuth service set it at startup:
https://github.com/GluuFederation/community-edition-setup/blob/master/templates/jetty/asimba#L3

**Comment by dmogn** [comment]
@yurem - Ok, Thanks!
Fixing...

**Comment by dmogn** [comment]
Done.
