### ISSUE TITLE
Add certificate exception (SP or IDP)

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#37]
Ubuntu 14.04; gluu-server v.3.0.1

2017-03-27 14:52:49,913 INFO  [qtp274064559-12] [org.gluu.oxtrust.action.UpdateAsimbaIDPAction] (UpdateAsimbaIDPAction.java:220) - uploadCertificateFile() call for IDP
2017-03-27 14:52:49,918 WARN  [qtp274064559-12] [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] (AsimbaXMLConfigurationService.java:153) - Certificate parsing exception
java.lang.ClassCastException: org.bouncycastle.cert.X509CertificateHolder cannot be cast to java.security.cert.X509Certificate
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificateStatic(SSLService.java:116) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificate(SSLService.java:89) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]

**Comment by dmogn** [comment]
Command: keytool -import -trustcacerts -alias https://ce.gluu.info/shibboleth -file shibIDP.crt -keystore asimbaIDP.jks

- works well for same certificate.
