### ISSUE TITLE
Asimba LDAP exception in 3.1.0 RC3

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#41]
Since 3.1.0 RC3 Ubuntu 14.04 (in RС2 and before works well).

> (ASIMBAWA) [2017-08-18 16:29:11] [INFO] LDAPConnectionProvider Attempting to create connection pool: 1
> (ASIMBAWA) [2017-08-18 16:29:11] [INFO] LDAPConnectionProvider Attempting to use older SSL protocols
> LDAPException(resultCode=81 (server down), errorMessage='An error occurred while attempting to send the LDAP message to server localhost:1636:  SSLException(message='Connection has been shutdown: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Unable to load trust store '/etc/certs/openldap.pkcs12' of type 'pkcs12':  java.io.IOException: keystore password was incorrect', trace='checkEOF(SSLSocketImpl.java:1541) / checkWrite(SSLSocketImpl.java:1553) / write(AppOutputStream.java:71) / flushBuffer(BufferedOutputStream.java:82) / flush(BufferedOutputStream.java:140) / sendMessage(LDAPConnectionInternals.java:543) / sendMessage(LDAPConnection.java:4249) / process(SimpleBindRequest.java:551) / bind(LDAPConnection.java:2143) / createConnection(LDAPConnectionPool.java:1268) / createConnection(LDAPConnectionPool.java:1178) / <init>(LDAPConnectionPool.java:1115) / <init>(LDAPConnectionPool.java:997) / <init>(LDAPConnectionPool.java:934) / <init>(LDAPConnectionPool.java:877) / <init>(LDAPConnectionPool.java:792) / createConnectionPoolImpl(LDAPConnectionProvider.java:218) / createConnectionPoolWithWaitImpl(LDAPConnectionProvider.java:188) / init(LDAPConnectionProvider.java:143) / <init>(LDAPConnectionProvider.java:68) / getLDAPEntryManager(LDAPUtility.java:163) / getLDAPEntryManagerSafe(LDAPUtility.java:174) 
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.createConnection(LDAPConnectionPool.java:1289)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.createConnection(LDAPConnectionPool.java:1178)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:1115)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:997)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:934)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:877)
>         at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:792)
>         at org.gluu.site.ldap.LDAPConnectionProvider.createConnectionPoolImpl(LDAPConnectionProvider.java:218)
>         at org.gluu.site.ldap.LDAPConnectionProvider.createConnectionPoolWithWaitImpl(LDAPConnectionProvider.java:188)
>         at org.gluu.site.ldap.LDAPConnectionProvider.init(LDAPConnectionProvider.java:143)
>         at org.gluu.site.ldap.LDAPConnectionProvider.<init>(LDAPConnectionProvider.java:68)
>         at org.gluu.asimba.util.ldap.LDAPUtility.getLDAPEntryManager(LDAPUtility.java:163)
>         at org.gluu.asimba.util.ldap.LDAPUtility.getLDAPEntryManagerSafe(LDAPUtility.java:174)
>         at org.gluu.asimba.util.ldap.LDAPUtility.<clinit>(LDAPUtility.java:83)
>         at org.gluu.asimba.engine.requestor.ldap.LDAPFactory.start(LDAPFactory.java:129)
>         at com.alfaariss.oa.engine.core.Engine.start(Engine.java:508)

**Comment by dmogn** [comment]
[14:04:27] Yuriy Movchan: AppInitializer->EncryptionService->PropertiesDecrypter.decryptProperties
- add new property

**Comment by dmogn** [comment]
Fixed.
