### ISSUE TITLE
Requestor cannot find Metadata for URL metadata

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/gluu-Asimba#8]
(ASIMBAWA) [2016-03-07 03:11:27] [WARN] SAML2Requestor No optional available metadata for requestor with id: https://ce.gluu.info/shibboleth
(ASIMBAWA) [2016-03-07 03:11:27] [DEBUG] AuthenticationRequestProtocol Can't trust AssertionConsumerServiceURL 'https://ce.gluu.info/Shibboleth.sso/SAML2/POST' supplied in request: _7fef233aced0fbc218a67cdbf2f364ab
(ASIMBAWA) [2016-03-07 03:11:27] [ERROR] AuthenticationRequestProtocol No SPSSODescriptor in metadata: Can't resolve response target for request: _7fef233aced0fbc218a67cdbf2f364ab
(ASIMBAWA) [2016-03-07 03:11:27] [DEBUG] WebBrowserSSO The request was invalid, so try to send a SAML error response
(ASIMBAWA) [2016-03-07 03:11:27] [WARN] WebBrowserSSO No destination for response available
(ASIMBAWA) [2016-03-07 03:11:27] [INFO] EventLogger null, null, null, null, null, 192.168.1.8, 2, REQUEST_INVALID, null, SAML2 Profile, null
(ASIMBAWA) [2016-03-07 03:11:27] [ERROR] OAServlet Could not process request
com.alfaariss.oa.OAException: 0001
        at com.alfaariss.oa.profile.saml2.profile.sso.WebBrowserSSO.sendResponse(WebBrowserSSO.java:865)
        at com.alfaariss.oa.profile.saml2.profile.sso.WebBrowserSSO.processAuthenticationRequest(WebBrowserSSO.java:576)
        at com.alfaariss.oa.profile.saml2.profile.sso.WebBrowserSSO.processSAMLRequest(WebBrowserSSO.java:484)
        at com.alfaariss.oa.profile.saml2.profile.sso.WebBrowserSSO.process(WebBrowserSSO.java:309)
        at com.alfaariss.oa.profile.saml2.SAML2Profile.service(SAML2Profile.java:281)
        at com.alfaariss.oa.OAServlet.service(OAServlet.java:245)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dmogn** [comment]
The internal code accepts null for some internal structures and fails for empty string "" value.
Fixed.

**Comment by dmogn** [comment]
Tested. Found and fixed the bug with IDP timeout lost 
https://github.com/GluuFederation/oxTrust/issues/208.
